name: Cache Dependencies
description: This Action Helps in Caching the dependencies if there are no changes in package-lock.json if not it install the respective dependencies
inputs:
  caching:
    description: Describes whether we wanna have caching or not
    required: false
    default: 'true'
outputs:
  used-cache-or-not:
    description: Specifies Whether we had used the Cache or not
    value: ${{steps.install.outputs.cache}}
runs:
  using: composite
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache='${{inputs.caching}}'" >> $GITHUB_OUTPUT
      shell: bash